openapi: 3.0.2
info:
  title: 'Example site'
  version: 0.1.0
x-walder-resources:
  path: ./
  views: views
  pipe-modules: pipeModules
  public: public
x-walder-datasources:
  - http://fragments.dbpedia.org/2016-04/en
paths:
  /music/{musician}:
    get:
      summary: Returns a list of songs of the given musician.
      parameters:
        - in: path
          name: musician
          required: true
          schema:
            type: string
          description: The target musician
      x-walder-query:
        $ref: './example/walderQueryInfo/music_musician_info.yaml'
      responses:
        200:
          description: list of songs
          x-walder-input-text/html: songs.handlebars
  /movies/{actor}:
    get:
      summary: Returns a list of the all movies the given actor stars in
      parameters:
        - in: path
          name: actor
          required: true
          schema:
            type: string
          description: The target actor
      x-walder-query:
        $ref: './example/walderQueryInfo/movies_actor_info.yaml'
      responses:
        200:
          description: list of movies
          x-walder-input-text/html: movies.pug
x-walder-errors:
  404:
    description: page not found error
    x-walder-input-text/html: error404.html
  500:
    description: internal server error
    x-walder-input-text/html: error500.html
