openapi: 3.0.2
info:
  title: 'Example site'
  version: 0.1.0
x-walder-resources:
  path: ./
  views: views
  pipe-modules: pipeModules
  public: public
x-walder-datasources:
  - http://fragments.dbpedia.org/2016-04/en
paths:
  /music/{musician}:
    get:
      summary: Returns a list of songs of the given musician, sorted in descending order by label and duplicate artists are removed.
      parameters:
        - in: path
          name: musician
          required: true
          schema:
            type: string
          description: The target musician
      x-walder-query:
        graphql-query: >
          {
            label @single
            writer(label_en: $musician)  @single
            artist  @single(scope: all) {
              label
            }
          }
        json-ld-context: >
          {
            "@context": {
              "label": "http://www.w3.org/2000/01/rdf-schema#label",
              "label_en": { "@id": "http://www.w3.org/2000/01/rdf-schema#label", "@language": "en" },
              "writer": "http://dbpedia.org/ontology/writer",
              "artist": "http://dbpedia.org/ontology/musicalArtist"
            }
          }
        options:
          sort:
            selectors:
              - object:
                  value: artist
                  selector: label
                  order: desc
          remove-duplicates:
            object:
              value: artist
              selector: label
      responses:
        200:
          description: list of songs
          x-walder-input-text/html: songs.handlebars
x-walder-errors:
  404:
    description: page not found error
    x-walder-input-text/html: error404.html
  500:
    description: internal server error
    x-walder-input-text/html: error500.html
