openapi: 3.0.2
info:
  title: 'Example site'
  version: 0.1.0
x-walder-resources:
  root: ./
  views: views
  pipe-modules: pipeModules
  public: public
x-walder-datasources:
  - https://data.knows.idlab.ugent.be/person/office/#
paths:
  /:
    get:
      summary: Home!
      x-walder-query:
        sparql-query: >
          PREFIX foaf: <http://xmlns.com/foaf/0.1/>
          PREFIX schema: <http://schema.org/>
          CONSTRUCT {
            ?id schema:name ?name;
             a schema:Publication;
             schema:abstract ?abstract;
             schema:datePublished ?date;
             schema:author [
                  foaf:name ?fName
             ].
          } WHERE
          {
           ?id schema:name ?name;
               schema:abstract ?abstract;
               schema:contributor <https://data.knows.idlab.ugent.be/person/office/#>;
               schema:datePublished ?date;
               schema:author [
            		foaf:name ?fName
               ].
          }
          LIMIT 1000
#        json-ld-frame: >
#          {
#            "@context": {"@vocab": "http://schema.org/",
#                         "fname": {"@id": "http://xmlns.com/foaf/0.1/name"}},
#             "@type": "http://schema.org/Publication"
#          }
        datasources:
          additional: true
          sources:
            - https://data.knows.idlab.ugent.be/person/office/publications.ttl
            - https://data.verborgh.org/ruben
            #- $ref: './publication-data-sources.yml'
            - https://dylanvanassche.be/publications/
            - https://julianrojas.org/
            #- http://localhost:3000/sparql
            - https://hvdsomp.info/index.ttl # This is different from Herbert's WebID.
            #- $ref: './employee-data-sources.yml'
            #- $ref: './alumni-data-sources.yml'
            - https://data.knows.idlab.ugent.be/person/office/employees-extra # Contains foaf:name of people who don't have it by default.
      responses:
        200:
          description: test
          x-walder-input-text/html: knows-home.pug
x-walder-errors:
  404:
    description: page not found error
    x-walder-input-text/html: error404.html
  500:
    description: internal server error
    x-walder-input-text/html: error500.html
