openapi: 3.0.2
info:
  title: 'Example site'
  version: 0.1.0
x-walter-resources:
  path: ./
  views: views
  pipe-modules: pipeModules
  public: public
x-walter-datasources:
  - http://fragments.dbpedia.org/2016-04/en
paths:
  /bad_query:
    get:
      summary: Returns a status 500 error page - bad query.
      x-walter-query:
        graphql-query: >
          {
            id @single
            ... {  # This will cause an error
              starring(label: "Brad Pitt") @single
            }
          }
        json-ld-context: >
          {
            "@context": {
              "Film": "http://dbpedia.org/ontology/Film",
              "label": { "@id": "http://www.w3.org/2000/01/rdf-schema#label", "@language": "en" },
              "starring": "http://dbpedia.org/ontology/starring"
            }
          }
      responses:
        200: movies.handlebars
  /bad_pipeModule:
    get:
      summary: Returns a status 500 error page - bad pipe module.
      x-walter-query:
        graphql-query: >
          {
            id @single
            ... on Film{
              starring(label: "Brad Pitt") @single
            }
          }
        json-ld-context: >
          {
            "@context": {
              "Film": "http://dbpedia.org/ontology/Film",
              "label": { "@id": "http://www.w3.org/2000/01/rdf-schema#label", "@language": "en" },
              "starring": "http://dbpedia.org/ontology/starring"
            }
          }
      postprocessing:
        filterT:
          source: filterT_bad.js
      responses:
        200: movies.handlebars
x-walter-errors:
  404:  error404.html
  500:  error500.html