openapi: 3.0.2
info:
  title: 'Example site'
  version: 0.1.0
x-walder-resources:
  root: ./
  views: views
  pipe-modules: pipeModules
  public: public
x-walder-datasources:
  - http://fragments.dbpedia.org/2016-04/en
paths:
  /bad_query:
    get:
      summary: Returns a status 500 error page - bad query.
      x-walder-query:
        graphql-query: >
          {
            id @single
            ... {  # This will cause an error
              starring(label: "Brad Pitt") @single
            }
          }
        json-ld-context: >
          {
            "@context": {
              "Film": "http://dbpedia.org/ontology/Film",
              "label": { "@id": "http://www.w3.org/2000/01/rdf-schema#label", "@language": "en" },
              "starring": "http://dbpedia.org/ontology/starring"
            }
          }
      responses:
        200:
          description: list of movies
          x-walder-input-text/html: movies.handlebars
  /bad_pipeModule:
    get:
      summary: Returns a status 500 error page - bad pipe module.
      x-walder-query:
        graphql-query: >
          {
            id @single
            ... on Film{
              starring(label: "Brad Pitt") @single
            }
          }
        json-ld-context: >
          {
            "@context": {
              "Film": "http://dbpedia.org/ontology/Film",
              "label": { "@id": "http://www.w3.org/2000/01/rdf-schema#label", "@language": "en" },
              "starring": "http://dbpedia.org/ontology/starring"
            }
          }
      x-walder-postprocessing:
        filterT:
          source: filterT_bad.js
      responses:
        200:
          description: list of movies
          x-walder-input-text/html: movies.handlebars
x-walder-errors:
  404:
    description: page not found error
    x-walder-input-text/html: error404.html
  500:
    description: internal server error
    x-walder-input-text/html: error500.html
