default:
  image: node:10.16.3

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

testing:lts:
  stage: test
  script: yarn test

testing:latest:
  image: node:latest
  stage: test
  script: yarn test
