nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.5.1.cjs

packageExtensions:
  "graphql-ld-comunica@*":
    dependencies:
      "stream-to-string": "*"
  "@comunica/query-sparql@*":
    dependencies:
      "@comunica/bus-query-operation": "*"
  "@comunica/actor-rdf-join-symmetrichash@*":
    dependencies:
      "@comunica/bus-query-operation": "*"
  "@comunica/actor-rdf-join-nestedloop@*":
    dependencies:
      "@comunica/bus-query-operation": "*"
  "@comunica/actor-rdf-resolve-quad-pattern-rdfjs-source@*":
    dependencies:
      "@comunica/bus-rdf-resolve-quad-pattern": "*"
  "@comunica/actor-abstract-path@*":
    dependencies:
      "@comunica/bus-query-operation": "*"
  "@comunica/actor-query-operation-path-inv@*":
    dependencies:
      "sparqlalgebrajs": "*"
