datasources:
  sparql:
    - http://dbpedia.org/sparql
paths:
  /movies/brad_pitt:
    get:
      summary: Returns a list of the all movies Brad Pitt stars in
      graphql-query: >
        {
          id @single
          ... on Film {
            starring(label: "Brad Pitt") @single
          }
        }
      json-ld-context: >
        {
          "@context": {
            "Film": "http://dbpedia.org/ontology/Film",
            "label": { "@id": "http://www.w3.org/2000/01/rdf-schema#label", "@language": "en" },
            "starring": "http://dbpedia.org/ontology/starring"
          }
        }
      postprocessing:
        filter:
          source: https://raw.githubusercontent.com/driesmarzougui/random/master/filter.js
      html: TBD